version: "3.8"

services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  ai-service:
    build: ./ai-service
    ports:
      - "6000:6000"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: smartcart
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smartcartdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: